version: '3.8'
services:
  mosquitto:
    image: mosquitto
    build: 
      context: ..
      dockerfile: docker/mosquitto/Dockerfile
    volumes:
      - ./mosquitto/config:/mosquitto/config
    environment:
      MOSQUITTO_PLUGIN_AUTH_BACKEND_URL : http://mock:80/auth
  mock:
    image: mock
    build: 
      context: mock
      dockerfile: Dockerfile
    volumes:
      - ./mock/app:/app
  test:
    image: test
    build:
      context: test
      dockerfile: Dockerfile
    volumes:
      - ./test/:/opt/test/
    depends_on: [mosquitto]
